name: Python application

on:
  push:

    branches: [ 'master', '-master' ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Build docker image
        run: |
          docker build -t web_screen .
      - name: Move to tests directory
        run: |
          docker run web_screen sh -c "cd /app/tests && pytest"