name: Python application

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Build docker image
        run: |
          docker build -t movie_maker .
      - name: test movie_maker
        run: |
          docker run movie_maker sh -c "pip install . && cd /app/tests && pytest"